name: wannaanime
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.8.1
  cached_network_image: ^3.1.0+1
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  http: ^0.13.4
  image: ^3.1.0
  intl: ^0.17.0
  palette_generator: ^0.3.2
  provider: ^6.0.1
  share: ^2.0.4
  shared_preferences: ^2.0.9
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: lookea-line
      fonts:
      - asset: assets/fonts/lookea-line.ttf
